### ISSUE TITLE
Ability to combine/separate voices

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#1]

**Comment by seemantk** [comment]
About to commit this set of fixes.

**Comment by seemantk** [comment]
Assigning this to @curran

**Comment by curran** [comment]
Solved in #27

**Comment by curran** [comment]
@seemantk Reopening this issue, as the previously working implementation that handled the reference lines correctly is no longer being used. Any ideas on how we can approach implementing the split/combine of the reflines in the new world of SVG that we have now? The path is not clear to me, will investigate further. This seems like one of the last big things we need to resolve.

**Comment by seemantk** [comment]
@curran,  thank you for reopening this.  I have an idea that I'd like to
flesh out, but it's hard to do in words (easier to draw).

Would you like to do a video hangouts/skype call in the next day or so?


*--*
*Oakland Finish Up Weekend*
Be Amazed.  Be Amazing.
Get Mentored | Get Inspired | *Finish* *Up*
http://oaklandfinishup.com

**Comment by curran** [comment]
Closed in **Combine separate reflines** #114
