### ISSUE TITLE
Encode rhythmic activity (attack density) as ribbon width

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#10]

**Comment by gworthey** [comment]
Jesse describes this simply as follows: "In a single given measure, add up the total number of notes in all the voices: that total represents the attack density." Hopefully this confirms your understanding, @curran and @seemantk!

**Comment by curran** [comment]
Awesome, thank you for the clarification here. The ribbons are coming along over at #71. This attack density computation can fit in there as the windowed computation. We can adjust the parameters to compute for each bar - a step size of 4 and a window interval of 4. We may run into trouble if the mensuration changes mid-song, but this will definitely work to get us started.

**Comment by curran** [comment]
We implemented the attack density computation using the algorithm described above. Here is [the implementation](https://github.com/sul-cidr/josquin-ribbon/pull/71/commits/99cdafc5161e35aab97fe326914f35120a6ec7c8#diff-21cc978204e78587b9d3af2109573897R124) for review.

Here's what the attack density ribbon looks like:

![image](https://cloud.githubusercontent.com/assets/68416/19474810/f10e9440-954e-11e6-9a5d-3942c3ba396a.png)

**Comment by curran** [comment]
Just as an experiment, here's what it looks like if the ribbons are always centered on middle C:

![image](https://cloud.githubusercontent.com/assets/68416/19474966/7b71861a-954f-11e6-90d8-bf237b313bed.png)

This gives more of a histogram-ish view.

**Comment by curran** [comment]
This was implemented in #71. Closing.
