### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#111]
Not sure which license, maybe MIT or BSD3?

**Comment by curran** [comment]
Maybe Apache?

**Comment by curran** [comment]
@versae @csbailey5t @gworthey Please let us know if you'd like us to generate a LICENSE file under a specific license.

Pending a license specification, @seemantk I think this issue can be left in the hands of Stanford folks.

As a note for whoever picks this up in the future: What I'd do to create the LICENSE file is create a new repository in GitHub, selecting the license type in the process, so GitHub will generate a LICENSE file in the new repository, then just copy that into this repo, perhaps changing the copyright holder.

**Comment by curran** [comment]
I will add a BSD3 LICENSE file. I believe this is what we had discussed.

**Comment by gworthey** [comment]
For the record, here's the BSD2 license used for software in Craig's related projects: https://github.com/craigsapp/humlib/blob/master/LICENSE.txt

This confirms that BSD3 was a reasonable choice for us!
