### ISSUE TITLE
Add notes on Jekyll in README

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#112]
For folks coming to the project like @csbailey5t @versae , it would be good to explain that you need to serve the site locally with `jeykll serve`, or `jekyll serve --watch`. Also installation notes for Jekyll might be nice.

**Comment by seemantk** [comment]
Do you think it's worth summarizing the contents of [GitHub's official documentation](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/)?

Actually, yeah it would be worth it to summarize the relevant  [relevant section](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/).

**Comment by curran** [comment]
Yes indeed! Also we can potentially use this documentation from this [other project that uses Jekyll](https://github.com/cfinst/cfinst.github.io/blob/master/README.md):

## Running this Site

This site is organized using [Jekyll](https://jekyllrb.com/). Jekyll runs automatically on [GitHub Pages](https://pages.github.com/), which is the main deployment strategy at the moment.

To run this site on your own machine, you'll need a working [Ruby](https://www.ruby-lang.org/en/documentation/installation/) environment. (For windows, you can download and run [RubyInstaller for Windows](https://rubyinstaller.org/).  For Linux or Macm you can use [rvm](http://rvm.io)). Then use the following commands:

```
# Install Jekyll on your machine (only required once).
gem install jekyll

# Use Jekyll to serve this site.
cd <repo directory here>
jekyll serve --watch
```
