### ISSUE TITLE
Measure-based fixed scaling

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#12]

**Comment by curran** [comment]
I believe the "Omniglass" PR #73 kind of implements this - when you click out of the brushed region, the scaling is always constant (the window size is fixed), which I believe is the crux of this feature (if my memory serves me well on what this issue is about).

**Comment by seemantk** [comment]
@curran, can we close this ticket in that case?

**Comment by curran** [comment]
@seemantk Actually, I think this is the same as the recent issue that Jesse brought up, where each measure should be a fixed width. I don't think we can close it quite yet.

To clarify, I think to close this ticket we need to make it so the widths of the bars are fixed through the mensuration changes here:
![image](https://cloud.githubusercontent.com/assets/68416/23708695/d7138886-043c-11e7-9dab-7f09f004662c.png)

In this screenshot we can see that the width changes (because note time is in terms of beats). When the mensuration changes, apparently the time occupied by one beat also changes, such that the time occupied by one measure stays the same.

I was trying to think of how we can implement this. We'll need to somehow correlate which notes fall into which mensurations, and divide the time (or something) based on which mensuration it is. The simplest way might be to try coming up with a function that will take as input a time in "beat time", and output a time in "absolute time" taking into account mensuration changes. Once we have a function like this, we can just pass all of the start time and end time values through it before rendering.

**Comment by curran** [comment]
Adding my thoughts/notes on working through the implementation here.

![image](https://cloud.githubusercontent.com/assets/68416/23950101/da7fe154-09af-11e7-9baa-9e6bcfb9f27f.png)

The above is what gets output from 

```js
  console.log(proll.barlines.map(function (d){
    return d.mensuration;
  }));
```

I think this data can be used to scale the time values for the notes.

**Assumption:** where "mensuration" is `undefined`, we can assume it has the same value as it did previously.

**Assumption:** "C|" means 4/4 time signature, "3" means 3/4 time signature.

Idea for implementation: replace the `starttime` values for all the notes to be in units of "fractions of a measure". How the note gets scaled will depend on the cumulative mensuration changes leading up to that note. Some examples:

Mensuration of "C|" for the first measure:

 * 1 → 0
 * 2 → 0.25
 * 3 → 0.5
 * 4 → 0.75

Mensuration of "3" for the first measure:

 * 1 → 0
 * 2 → 0.3333
 * 3 → 0.6666

Once the  `starttime` values are transformed, I believe we can just pass the resulting dataset in through the visualization and everything will "just work" - except the barlines will not be scaled properly.

Actually, this change would greatly simplify how we handle the barlines in terms of rendering them as well as computing their ticks. Since bars will be consistently spaced after this change, we can *simply just use* standard D3 axes for the lines and labels.

Let's confirm that there's no desire to ever render the piece with beat-based scaling. I'm not 100% sure I should clobber what we have now. Maybe there should be another check box to switch between beat-based scaling and measure-based scaling? This is a question for Jesse I think.

**Comment by curran** [comment]
As a first step, we can fill in the mensurations for all bars based on the last known value:

![image](https://cloud.githubusercontent.com/assets/68416/23952531/b8476672-09b7-11e7-9ea8-69516d14a96b.png)

```js
  var mensuration;
  console.log(proll.barlines.map(function (d){
    return mensuration = (d.mensuration || mensuration);
  }));
```

**Comment by curran** [comment]
Discovered a truism that holds for all bars that may come in handy:

```js
(+d.label) === (i + 1)
```

**Comment by curran** [comment]
As the next step, we convert mensuration symbols to their "number of beats per bar" equivalent:

![image](https://cloud.githubusercontent.com/assets/68416/23952878/e3dfe16e-09b8-11e7-9ba5-866153dbde93.png)

**Comment by curran** [comment]
Here we go, I think this is the scaling we're after: https://github.com/sul-cidr/josquin-ribbon/pull/117/commits/56dbfdbedb138baf962cbfa6d94e646e4412f1a6

![image](https://cloud.githubusercontent.com/assets/68416/23953559/f7755496-09ba-11e7-8ff2-d409eb60abcf.png)

![image](https://cloud.githubusercontent.com/assets/68416/23953616/25a5dfca-09bb-11e7-9269-a5a1d0f2789f.png)

**Comment by curran** [comment]
Judging by the number of beats in this note that occupies a complete measure in "C|" time,

![image](https://cloud.githubusercontent.com/assets/68416/24100209/24a9327a-0d99-11e7-959a-6ff71e868ba5.png)

I believe the correct number of beats per bar for "C|" time is 8, not 2 or 4 as I previously thought.

**Comment by curran** [comment]
Just discovered that the number of beats per measure for mensuration "3" is 12 (`jos1913`).

![image](https://cloud.githubusercontent.com/assets/68416/24200522/4e56e900-0f33-11e7-95ad-3dd3ee6587e2.png)

**Comment by seemantk** [comment]
This is looking great, @curran!

I think I see how we can rescale the image properly after switching.

do the ribbons need to be recalculated as well? :/

**Comment by curran** [comment]
@seemantk Yes, unfortunately I neglected the Ribbons. Will investigate.
