### ISSUE TITLE
Make sure split/combine works across back/forward buttons

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#135]

**Comment by gworthey** [comment]
I don't think I understand this requirement: back and forward buttons would normally take us to an entirely new piece, which one would reasonably expect to appear in its default state, not in whatever state the previous piece was in.

Is there a case where the back button takes us to a different state of the same piece?

**Comment by seemantk** [comment]
Closing as out of scope (as discussed on our call 2 weeks ago).
