### ISSUE TITLE
Fit interface to window

### ISSUE THREAD

**Issue by craigsapp** [sul-cidr/josquin-ribbon#159]
When loading the ribbon plotter into a web browser window, I am getting an extra margin at the top and the bottom of the navigator is clipped:

![screen shot 2017-08-30 at 7 20 24 am](https://user-images.githubusercontent.com/3487289/29877276-024fe3b4-8d54-11e7-82fd-a2d495ac1884.png)

The height of the extra margin is not the same as the clipping on the navigator, so they are probably not related:

![screen shot 2017-08-30 at 7 22 55 am](https://user-images.githubusercontent.com/3487289/29877312-1beeb25a-8d54-11e7-905b-489c95924635.png)

When I resize the page, the clipping remains, so I have to scroll to the bottom of the page to see the full navigator.  But then the title at the top is clipped:

![screen shot 2017-08-30 at 7 24 27 am](https://user-images.githubusercontent.com/3487289/29877363-44cf76be-8d54-11e7-93df-c68996abe0a0.png)

**Comment by seemantk** [comment]
Hi @craigsapp!

Welcome back!  This is as expected. Due to the complexity and detail, the
visualization elements together (main + nav) occupy 100% of the height in
this resolution.  The title, being static, is not considered part of the
viz itself.

Hope this helps.
Cheers,
Seemant

**Comment by curran** [comment]
I think this is fine to close?

**Comment by csbailey5t** [comment]
Closed as finished. Further style modification relevant to this can be handled in integration into humdrum.
