### ISSUE TITLE
Zoom in on page load

### ISSUE THREAD

**Issue by craigsapp** [sul-cidr/josquin-ribbon#160]
When the ribbon plotter is first opened, the navigator selection is 100%.  This makes it confusing for first time users as to what the meaning of the navigator is, and that the box on the navigator is a box rather than a background color.

It would be useful to only show the first 1/8th of the music in the top plot when loading the page so that the navigator box is smaller and should allow faster discovery of what its function is:

![screen shot 2017-08-30 at 7 27 55 am](https://user-images.githubusercontent.com/3487289/29877540-c0ca5f54-8d54-11e7-8512-3dbbddafe8f0.png)

Optionally the size of the box could initially be made proportional to the zoom view above it, or the ratio of the  width to height of the initial navigator box could be 1.62.

**Comment by gworthey** [comment]
In my opinion, this is a matter of taste and preference, not part of the original spec (and possibly not even desirable).  In practice, if #149 (include state values in URL -- also a new feature) were to be resolved, it seems like this default zoom preference could be addressed.
