### ISSUE TITLE
left justification of mensurations and section titles

### ISSUE THREAD

**Issue by craigsapp** [sul-cidr/josquin-ribbon#162]
A mensuration or new section starts at a given barline, so techncially these symbols should be left-justified to the measure they start in rather than centered:

![screen shot 2017-08-31 at 5 41 47 pm](https://user-images.githubusercontent.com/3487289/29950909-e6f8e0ae-8e73-11e7-9d01-23882548e9a7.png)

Better as:

![zzzzz](https://user-images.githubusercontent.com/3487289/29950977-53c1f162-8e74-11e7-974b-e4400c3ddc3b.png)

**Comment by craigsapp** [comment]
Left-justification will fix this case at the start of:

http://ribbon.humdrum.org/?id=Jos2510

![screen shot 2017-08-31 at 5 52 50 pm](https://user-images.githubusercontent.com/3487289/29951111-4c67ccce-8e75-11e7-97ae-fe7d3a7ec564.png)

**Comment by craigsapp** [comment]
Note that it is possible to have section titles overlap (which would not be fixed by left alignment):

![screen shot 2017-08-31 at 5 59 28 pm](https://user-images.githubusercontent.com/3487289/29951244-3ffa6c98-8e76-11e7-857e-b69a1840cab0.png)

**Comment by curran** [comment]
Closed in https://github.com/sul-cidr/josquin-ribbon/pull/182
