### ISSUE TITLE
Scaled measure view only

### ISSUE THREAD

**Issue by craigsapp** [sul-cidr/josquin-ribbon#164]
There will not be a need to view both the scaled and unscaled versions of the score, so this check box can be removed from the interface:

![screen shot 2017-09-05 at 12 50 54 pm](https://user-images.githubusercontent.com/3487289/30080655-2a3ff546-9239-11e7-84a0-d1388a94ccb8.png)

The algorithm for the use of x-axis scaling should be:

(1) If the time-in-second parameters are found in the JSON data, automatically display the time-scaled x-axis (what currently happens when the box is checked).
(2) If the time-in-second parameters are not found, then fall back to the score-time (unscaled) x-axis (what currently happens when the box is unchecked).

**Comment by curran** [comment]
Thanks @craigsapp for spelling this out. This is great to have as direction.
