### ISSUE TITLE
Possibly rename "Standard Deviation"

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#170]
to
 * Local Pitch Variation
 * Pitch Variation
 * Melodic Movement
 * Melodic Movement

**Comment by gworthey** [comment]
Per email from Jesse, October 4, 2017:

- Replace "Standard deviation" with "Melodic contour"
- Replace "Attack density" to "Rhythmic activity"

Both of these will need some sort of key, or legend, or tool tip, etc.
