### ISSUE TITLE
Add SVG export feature, wherein selected graphics can be exported to a file.

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#18]

**Comment by curran** [comment]
This seems like a good library https://github.com/Hypercubed/svgsaver

**Comment by curran** [comment]
Here's a bl.ock that demonstrates one way we could do this: [Download SVG from Data URL](http://bl.ocks.org/curran/7cf9967028259ea032e8). This would probably work for us.

**Comment by curran** [comment]
Notes from a recent call - the SVGs exported should be the "shadow" SVGs, without any viewbox applied. This will yield the SVG with a fixed height and the original aspect ratio in terms of note lengths, which is ideal for comparing the exported SVGs between different pieces.

**Comment by seemantk** [comment]
@curran my hypothesis is that you'll get better results by keeping the viewBox, but getting rid of the preserveAspectRatio attribute from the top level SVG in the export.  The viewBox attribute only establishes the coordinate system, while preserveAspectRatio tells it how to scale to fit into its container.  When you leave it out, it doesn't try to scale itself.

I think the downloaded SVG could look similar to how the #book and #nav svg's look, but without the preserveAspectRatio attribute in the topmost container svg.

I hope that made sense...(?)

**Comment by curran** [comment]
@seemantk Yes I think that makes sense. Thanks for the input, I'll definitely experiment with this when adding the export feature.

**Comment by seemantk** [comment]
[svjimmy](https://github.com/mbostock/svjimmy) has recently been released, and mbostock tested it (and made it work) on the josquin SVGs [at my request](https://github.com/mbostock/svjimmy/issues/1).

**Comment by curran** [comment]
@seemantk I realized that svjimmy only exports PNG files, not SVG files, so I'm not sure it will work for us actually. I'll go ahead and try using [SVGSaver](https://github.com/Hypercubed/svgsaver), which does account for styles I believe.
