### ISSUE TITLE
Remove pitch labels, maybe full staff from Rhythmic Activity ribbon view

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/josquin-ribbon#195]
Each voice's Rhythmic Activity ribbon would just appear in the center of its portion of the score.

**Need to clarify** the desired behavior when "Show Notes" is selected. Currently, the notes appear at their notated pitch levels, and the rhythmic activity ribbon seems to be centered vertically in the middle of each voice's range for the piece. This makes a certain amount of sense.

**Comment by broadwell** [comment]
Decision (for now): staff with pitch labels should reappear when "Show Notes" is selected for Rhythmic Activity ribbon.

**Comment by simonwiles** [comment]
Closed by #212.
