### ISSUE TITLE
Highlight highest and lowest notes

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#2]

**Comment by seemantk** [comment]
In progress currently.

**Comment by curran** [comment]
I'm thinking to embark on implementing this. I believe we had discussed adding an additional UI element (e.g. a check box) for highlighting the highest and lowest notes.

I think I'll tackle the work as follows:

 * [ ] Show the highest and lowest notes as red (all the time)
 * [ ] Set up a dispatch channel for toggling the highlight
 * [ ] Create a check box for toggling the highlight

**Comment by curran** [comment]
As a reference, this is what it looks like in the old Ribbon plot:

![image](https://cloud.githubusercontent.com/assets/68416/18045159/0a292742-6def-11e6-8b4f-ba9c861cdb42.png)
