### ISSUE TITLE
Hide Extreme Notes

### ISSUE THREAD

**Issue by craigsapp** [sul-cidr/josquin-ribbon#213]
"Hide Extreme Notes" is a misinterpretation: this should be "Highlight Extreme Notes".  The extreme notes should never actually be hidden (unless all notes are hidden).

<img width="608" alt="Screen Shot 2019-11-06 at 10 25 37 PM" src="https://user-images.githubusercontent.com/3487289/68365091-932d8980-00e4-11ea-9c62-c1d19007c762.png">

Notice that the extrema notes disappear:

<img width="523" alt="Screen Shot 2019-11-06 at 10 25 43 PM" src="https://user-images.githubusercontent.com/3487289/68365323-2961af80-00e5-11ea-914b-44eaf4e914ee.png">

Instead the extrema notes should be highlight, such as the original case where they were colored in red.

**Comment by broadwell** [comment]
The extreme-note hiding was implemented on the basis of the "Proposed Menu View" doc that was presumably provided to the developers by JR at some point towards the end of the last development phase (see screenshot). So it's not clear where the misinterpretation occurred.

![Screenshot 2019-11-07 15 58 05](https://user-images.githubusercontent.com/7329112/68438181-177d1c80-0178-11ea-8f68-a2fbb46e676d.png)

In any case, the "Highlight Extreme Notes" feature certainly does have much to recommend it, so there may indeed be a consensus to reintroduce it after the updated site is available for preview.

**Comment by craigsapp** [comment]
That looks like a typo which @jesserodin can clarify.  Otherwise hiding some notes but not others does not make sense.

**Comment by broadwell** [comment]
Yes it was indeed a typo! Restoring the highlight functionality...
