### ISSUE TITLE
Make extreme notes more prominent

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/josquin-ribbon#232]
There are a few fairly related approaches to this that we will pursue. An additional factor to consider is the degree to which the changes also will make the extreme notes more visible in an exported SVG that is printed in greyscale (as is likely to be the case with most physical publications).

- [x] Always draw notes layers above ribbons (at present, the layering is somewhat erratic).
- [x] Decouple "Show Notes" and "Highlight Extreme Notes" checkboxes (and their behavior) so that it's possible to turn on the highlighted extreme notes while the other notes remain invisible.
- [x] Experiment with different colors, shapes or stroke widths for the highlighted style.

**Comment by simonwiles** [comment]
Closed by #234 and #236.
