### ISSUE TITLE
Responsive SVG

### ISSUE THREAD

**Issue by seemantk** [sul-cidr/josquin-ribbon#33]
While demonstrating [pull request 32](https://github.com/sul-cidr/josquin-ribbon/pull/32) for Javier, @gworthey  and  @craigsapp on today's call, Craig noted that he would like the ribbons to stretch to fit a very wide screen.

Also, the visualization is likely to be a full-screen one (and won't have to necessarily fit into the regular josquin website template.

This ticket is a general ticket to ensure the SVG takes advantage of all available space.

**Comment by curran** [comment]
@seemantk Would you mind having a go at this one? I feel like you're more versed in the SVG scaling techniques than I. I have this bl.ock [Responding to Resize](http://bl.ocks.org/curran/3a68b0c81991e2e94b19), but perhaps using the SVG viewport and view box may be more elegant / easier.

**Comment by seemantk** [comment]
I'm working my way through this ticket. I've cleaned up the bootstrap and now working on the actual responsive part.
![bootstrapping](https://cloud.githubusercontent.com/assets/589271/19727597/e6b0768e-9b44-11e6-8268-173d00a24bca.png)

**Comment by curran** [comment]
Sweet! It looks great. I wonder if we could merge the progress so far?

**Comment by curran** [comment]
Sweet! It looks great. I wonder if we could merge the progress so far?

**Comment by curran** [comment]
@seemantk I feel this is pretty close, but I noticed an issue with the text where it gets distorted.

![image](https://cloud.githubusercontent.com/assets/68416/23247987/1684da80-f9c3-11e6-84df-679f031628f3.png)

![image](https://cloud.githubusercontent.com/assets/68416/23248009/37b9dfb6-f9c3-11e6-884f-5141653e6421.png)

Usually the aspect ratio is in a range where it doesn't look too distorted, but it would be really cool if we could get it so the text is not distorted at all.

Maybe we could adjust the SVG scaling properties so the aspect ratio is constant?

Any other ideas for how this might be done?

**Comment by seemantk** [comment]
The state of SVG support in browsers has a jaggedy edge. One of those is "transform=ref()" which does exactly what we want, but only in Opera browsers, a tiny minority.

So I asked AmeliaBR on twitter, and she responded with [some example codepens](http://codepen.io/collection/njbPRv/#) that might be illustrative.  Looks to be a good starting point for this.

**Comment by curran** [comment]
Awesome! Thanks for investigating. I wonder if it would work out well to just use `.attr("preserveAspectRatio", "xMinYMin meet")`

**Comment by seemantk** [comment]
Since our meeting last week, we changed this and we've now changed back to "none" preserveAspectRatio.

Per AmeliaBR, the trick is not to use a viewBox on the outermost SVG, and rather use them only where needed in the nested SVGs.

 I've started testing/playing locally with toy SVGs, and will report back during this week.

**Comment by seemantk** [comment]
Closing this as part of the work in #119.
