### ISSUE TITLE
Ensure that navigation ribbon and focus ribbon are visually distinct. 

### ISSUE THREAD

**Issue by seemantk** [sul-cidr/josquin-ribbon#34]
While demonstating [pull request 32](https://github.com/sul-cidr/josquin-ribbon/pull/32) for @craigsapp , @gworthey  and Javier this morning, Craig noted that there should be a visual distinction/separation between the navigation strip and focus strip (padding, line, background color, were all mentioned as possible avenues to pursue).

**Comment by curran** [comment]
Maybe a subtle border where the clip path lies would be suitable.

**Comment by seemantk** [comment]
Subtle borders exist around both svg elements now.  Closing.
