### ISSUE TITLE
Highlight globally highest and lowest notes

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#44]
As a follow-on to #2, the highest and lowest notes across all voices combined should be highlighted in combined mode.

The current solution does not look good in the combined view:

![image](https://cloud.githubusercontent.com/assets/68416/18045713/de40aaa8-6df1-11e6-909d-76e8f44717ce.png)

**Comment by curran** [comment]
Actually, maybe we don't need to do this after all. On one of our recent calls, @craigsapp mentioned that it's nice in a way to see the minimum and maximum pitches per voice even in the combined view. He also made the point that the global minimum and maximum pop out visually anyway, so perhaps hiding the internal ones doesn't get us much.

One downside of the current approach (adding a thick red stroke) is that you can't tell which of the internal red outlines corresponds to which voice. Maybe we could experiment with using the original colors, and highlighting the extreme notes in another way - perhaps just using a thick stroke with the original color.

**Comment by curran** [comment]
This was confirmed by Jesse - that we _should indeed_ only highlight the globally highest and lowest notes in the combined view.

**Comment by curran** [comment]
Pending feedback from @craigsapp / Jesse on what the desired behavior is.

**Comment by craigsapp** [comment]
Jesse agrees that the global view should mark the highest/lowers note of individual voices rather than display only the global max/min across all voices, so this particular feature should not be implemented.
