### ISSUE TITLE
Section lines and labels

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#5]

**Comment by curran** [comment]
Should look something like the red lines and yellow text here 
![image](https://cloud.githubusercontent.com/assets/68416/18134982/e865b122-6fbd-11e6-9ca6-5b764c67a141.png)

From http://josquin.stanford.edu/analysis/activity/

**Comment by gworthey** [comment]
Craig: please clarify where and how these labels and measure numbers appear in the data.

**Comment by gworthey** [comment]
Jesse reports that section labels appear in the humdrum data as follows:
`!!section: Kyrie II`

The ribbon should display the features noted above for section beginnings: 
- vertical line
- label
- mensuration sign

**Comment by curran** [comment]
I don't think these appear in the JSON data at all. Will do a deep dive search, then close this if I can't find any.

**Comment by seemantk** [comment]
found a piece with sections! http://ribbon.humdrumorg/?id=ano1001
in the data.json:
![section](https://cloud.githubusercontent.com/assets/589271/23981061/1dca9c4a-09c1-11e7-931f-dd66be6363d6.png)

**Comment by seemantk** [comment]
found a piece with sections! http://ribbon.humdrumorg/?id=ano1001
in the data.json:
![Uploading section.png…]()

**Comment by curran** [comment]
This was implemented in #122. Way to go @seemantk !

**Comment by curran** [comment]
For reference, this is what the implementation looks like for http://ribbon.humdrum.org/?id=ano1001 :

![image](https://cloud.githubusercontent.com/assets/68416/24200261/9bec19b6-0f32-11e7-8ea0-96b642a5d258.png)
