### ISSUE TITLE
Change X axis from beats to measures

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#60]
The changes introduced in #58 annotate the X axis with beats. This should be changed to use measure numbers, rather than beat numbers.

This is a follow-on to #3

**Comment by seemantk** [comment]
@curran, thanks for creating this ticket.  It's unclear where to find the measure numbers in the dataset.  Any guidance on that?

**Comment by curran** [comment]
@seemantk I believe the data for this is present in data.barlines as the "label" property of each bar.

For extracting the bars, you have the following:

``` js
bars = data.barlines.map(function(b) { return b.time[0]; });
```

Similarly, extracting the labels would be possible like this:

``` js
barLabels = data.barlines.map(function(b) { return b.label; });
```

I tested the above snippet and found that for the last bar, "label" is undefined in the data, so I think we could use the bar's index instead (but adding 1 to make it start at 1 like "label"), like this:

``` js
barLabels = data.barlines.map(function(b, i) { return i + 1; });
```

We can use this logic to place the labels on the bar lines, but then we have the issue that we lose the D3 axis goodness that calculates the appropriate density of ticks. We could emulate that, though, with some custom logic that hides the labels if they are too close.

**Comment by curran** [comment]
Will take a stab at this.

**Comment by curran** [comment]
I implemented the idea, here's what it looks like now (using the piece `#Das1002`):

![image](https://cloud.githubusercontent.com/assets/68416/18347389/dc2ca5ca-75e2-11e6-930a-4af527c9ea7e.png)

When the ticks get too dense, some are left out based on testing the distance from the previous tick:

![image](https://cloud.githubusercontent.com/assets/68416/18347419/fde44704-75e2-11e6-8103-fcf6558a675d.png)

The next level of label filtering looks like this:

![image](https://cloud.githubusercontent.com/assets/68416/18347436/195727d6-75e3-11e6-9692-87b4ff89a423.png)

The feature is achieved, but I don't like the odd subdivisions. I wish there were a way to leverage D3's intelligent axis ticks generation, then map it onto these bar lines. I'm not seeing a way to do that right now, but it may be possible somehow.

**Comment by curran** [comment]
Actually this approach might be the best, because it holds up well in the case of mensuration changes. Check out the change in subdivision here at measure 85:

![image](https://cloud.githubusercontent.com/assets/68416/18347699/8926390c-75e4-11e6-989f-ba77120000f9.png)
