### ISSUE TITLE
Overall Refactoring

### ISSUE THREAD

**Issue by curran** [sul-cidr/josquin-ribbon#64]
I'd like to take an initiative to refactor the codebase to minimize repetition. Some ideas I'd like to pursue here include:
- initialize the application by explicitly dispatching the initial state through all the dispatchers
- have the `my` method be a function that can be called many times and will act as a "rubber stamp" (as in the original [Towards Reusable Charts](https://bost.ocks.org/mike/chart/)).
- Consolidate the `update` functions into the `my` render functions, so that there are no longer two separate functions (one for initialization and another for updating), but rather a single render function.
- Store the container DOM element (`svg`) and imput data (`data`) via accessors, rather than passing them into the `my` function once on initialization and tracking them internally implicitly. This would allow us to eliminate the render functions like `renderNotesNav`. Also we would no longer need to track the DOM elements externally to the components, so we could get rid of the variables like `notesNavSVG`, `notesBookSVG`, `combineSeparateDiv`, etc.
- Eliminate default values within components (e.g. `margin`). Since we are in control of the complete code (the main program and the components), we can choose to force the main program to set the initial values for everything. This would eliminate lots of repetition.

Here are a few pieces of logic that are repeated throughout the codebase that I believe can be reduced to a single occurance:
- `margin = { top: 20, right: 20, bottom: 20, left: 20 }`
  - https://github.com/sul-cidr/josquin-ribbon/blob/gh-pages/js/baton.js#L3
  - https://github.com/sul-cidr/josquin-ribbon/blob/gh-pages/js/notesbook.js#L9
  - https://github.com/sul-cidr/josquin-ribbon/blob/gh-pages/js/notescanvas.js#L8
  - https://github.com/sul-cidr/josquin-ribbon/blob/gh-pages/js/notesnav.js#L9
- `colorScale = d3.scaleOrdinal(d3.schemeCategory10)`
  - https://github.com/sul-cidr/josquin-ribbon/blob/gh-pages/js/baton.js#L20
  - https://github.com/sul-cidr/josquin-ribbon/blob/c1eabf5e1970a20c049d325fb26a86c0c47192e3/js/legend.js#L7
- `{ x: [0, data.scorelength[0]], y: d3.range(data.minpitch.b7, data.maxpitch.b7)}`
  - https://github.com/sul-cidr/josquin-ribbon/blob/gh-pages/js/baton.js#L94
  - https://github.com/sul-cidr/josquin-ribbon/blob/gh-pages/js/notesbook.js#L61
  - https://github.com/sul-cidr/josquin-ribbon/blob/gh-pages/js/notescanvas.js#L44

**Comment by seemantk** [comment]
@curran, I love this idea to refactor (especially the my() stuff).  I've been thinking about object hierarchy stuff.

Can you explain a bit more about your thoughts around the DOM element and data accessors?

**Comment by curran** [comment]
@seemantk Cool! Yeah, the DOM element and data accessors would look like this:

https://github.com/sul-cidr/josquin-ribbon/blob/airplane-work/js/notesview.js#L208

Then part of the `my()` function contract is that both of those should be set before invoking it. Here's what the modified `my()` would look like:

https://github.com/sul-cidr/josquin-ribbon/blob/airplane-work/js/notesview.js#L37

I actually did some of this refactoring in the airplane on the way back to India, but by now this branch is out of date.

**Comment by curran** [comment]
I thought this would be a "multi-chapter" initiative, but I think I'll just leave things be, as the program is working well with the current structure, and a big refactoring may not be worth the effort at this point. Closing.
