### ISSUE TITLE
Switch to URL queries for song titles

### ISSUE THREAD

**Issue by seemantk** [sul-cidr/josquin-ribbon#68]
I think we should switch from hash notation to URL query strings (eg: `?song=Josquin-1913`) for the following reasons.
1. Browsers use the hash fragment identifier to place an id with the #'s name on the top of the page, ie loval navigation on the page. Github does this well, as this link to ordinal scales shows: `https://github.com/d3/d3/blob/master/API.md#ordinal-scales`
2. Consistency with the rest of the Josquin site: `http://josquin.stanford.edu/work/?id=Jos1912`

I've got some code that does this parsing, so I can take this on.

**Comment by curran** [comment]
Sounds good to me! I'm sure @craigsapp would be happy to see consistency with the rest of the Josquin site. In fact, I think he mentioned this when we debuted the hash navigation.

**Comment by seemantk** [comment]
Great!  I'll take this one on, then.
